"""Generate Divergent Association Task answers with an LLM.

Four methods:
  - direct: one-pass autoregressive generation of the whole 10-word answer
    (the protocol used by arXiv:2310.11158 and arXiv:2405.13012).
  - gibbs: initialise with a direct draw, then repeatedly resample one word
    conditioned on the other 9 using the LLM conditional (Large Language Gibbs).
  - direct_continuation / gibbs_continuation: same two schemes, but every word
    is generated by literal continuation of the partial JSON object (one LLM
    call per field; see sampling/continuation_llm.py) instead of one
    JSON-constrained call per prompt.

Answers are saved unscored; run evaluate.py afterwards (needs the GloVe assets
from download_assets.sh but no LLM).
"""

import argparse
import itertools
import json
import os
import random
import time
from copy import deepcopy
from pathlib import Path
from typing import Any

import numpy as np
from priorbot.llm import OpenAICompatLLM
from priorbot.priors import GibbsLLMPrior, LLMPrior
from tqdm import tqdm

from divergent_association_task.continuation import ContinuationWordLLM
from divergent_association_task.templates import create_continuation_template, create_template
from divergent_association_task.utils import (
    MODEL_NAME_TO_TYPE,
    RESULTS_DIR,
    build_schema,
    word_var_names,
)
from sampling.continuation_prior import ContinuationLLMPrior


class RecordedGibbsLLMPrior(GibbsLLMPrior):
    """GibbsLLMPrior that additionally records the full chain of states.

    The scan loop is copied from GibbsLLMPrior._sample_impl (as in
    consistent_reasoning.algorithms.gibbs.LoggedGibbsLLMPrior); the only
    addition is that every state, including the direct-sample initialisation,
    is kept so evaluate.py can plot DAT score against Gibbs step.

    sample_parallel runs one _sample_impl per schema concurrently, so chains
    are stored keyed by the pbar slot index; callers running more than one
    chain must pass pbar=True (as run.py does) so the slots are distinct.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.chains: dict[int, list[dict[str, Any]]] = {}
        self.resampled_keys: dict[int, list[list[str]]] = {}
        self._fallback_slot = itertools.count()

    def _sample_impl(
        self,
        n_samples: int,
        schema: dict[str, Any],
        observed: dict[str, Any] | None = None,
        verbose: bool = False,
        pbar: int | None = None,
    ) -> list[dict[str, Any]]:
        samples = self.llm_prior.sample(1, schema, verbose, False)
        chain = [samples[0].copy()]
        resampled: list[list[str]] = []

        chain_length = self.burn_in + n_samples * self.thinning
        keys_pool: list[str] = []
        for _ in tqdm(
            range(chain_length),
            disable=pbar is None,
            position=pbar,
            desc=f"Chain {pbar}",
            dynamic_ncols=True,
        ):
            current = samples[-1].copy()
            keys = list(current.keys())
            if self.shuffle_variables:
                np.random.shuffle(keys)

            if not self.sweep:
                keys_to_discard = keys[-self.block_size :]
            else:
                if len(keys_pool) < self.block_size:
                    keys_pool = keys_pool + keys
                keys_to_discard = keys_pool[: self.block_size]
                keys_pool = keys_pool[self.block_size :]

            itr_observed = {k: current[k] for k in keys if k not in keys_to_discard}
            itr_schema = {
                "type": "object",
                "properties": {key: schema["properties"][key] for key in keys_to_discard},
                "required": keys_to_discard,
            }

            all_observed = {**itr_observed, **(observed or {})}
            new_marginal = self.llm_prior.sample_conditional(1, itr_schema, all_observed, verbose)[
                0
            ]
            new_sample = itr_observed | new_marginal
            samples.append(new_sample)
            chain.append(new_sample.copy())
            resampled.append(list(keys_to_discard))

        slot = next(self._fallback_slot) if pbar is None else pbar
        self.chains[slot] = chain
        self.resampled_keys[slot] = resampled
        return samples[self.burn_in + self.thinning :: self.thinning][:n_samples]


def _to_word_lists(sample_dicts: list[dict[str, Any]], n_words: int) -> list[list[str]]:
    names = word_var_names(n_words)
    return [[sample[name] for name in names] for sample in sample_dicts]


def _save(path: Path, payload: dict[str, Any]) -> None:
    # Atomic write so the exists()-based resume never sees a partial file.
    tmp_path = path.with_name(path.name + ".tmp")
    with open(tmp_path, "w") as f:
        json.dump(payload, f)
    os.replace(tmp_path, path)
    print(f"Saved {len(payload['samples'])} answers to {path}")


def main(args: argparse.Namespace):
    out_dir = RESULTS_DIR / f"{args.model_name.replace('/', '--')}_temp{args.temperature}"
    out_dir.mkdir(parents=True, exist_ok=True)

    system_prompt = "" if args.model_type == "base" else "You are a helpful assistant."
    llm_common_kwargs = {
        "model_name": args.model_name,
        "base_url": args.base_url,
        "system_prompt": system_prompt,
        "use_chat_api": args.model_type == "instruct",
    }

    schema = build_schema(args.n_words)
    n_per_chain = args.n_samples // args.n_chains
    reasoning_tag = "_reasoning" if args.manual_reasoning else ""
    reasoning_extra_tokens = 1024 if args.manual_reasoning else 0
    common_meta = {
        "model_name": args.model_name,
        "model_type": args.model_type,
        "temperature": args.temperature,
        "n_words": args.n_words,
        "n_samples": args.n_samples,
        "n_chains": args.n_chains,
        "manual_reasoning": args.manual_reasoning,
        "seed": args.seed,
    }

    # 1. Direct sampling (single-pass, ancestral order word_1..word_N)
    direct_out_path = (
        out_dir / f"direct{reasoning_tag}_k{args.n_words}_nc{args.n_chains}_seed{args.seed}.json"
    )
    if "direct" not in args.methods:
        pass
    elif direct_out_path.exists():
        print(f"Results already exist at {direct_out_path}, skipping...")
    else:
        print("\n--- Running Direct Sampling ---")
        llm = OpenAICompatLLM(
            **llm_common_kwargs,
            temperature=args.temperature,
            max_tokens=args.n_words * 24 + reasoning_extra_tokens,
        )
        template = create_template(args)
        direct_prior = LLMPrior(
            llm=llm,
            template=template,
            shuffle_variables=False,
            manual_reasoning=args.manual_reasoning,
        )
        direct_prior.reasoning_prompt = direct_prior.reasoning_prompt.replace(
            "step-by-step", "brief"
        )
        t_start = time.time()
        chain_results = direct_prior.sample_parallel(
            n_per_chain,
            [deepcopy(schema) for _ in range(args.n_chains)],
            verbose=args.verbose,
            pbar=True,
        )
        samples = _to_word_lists([s for s_chain in chain_results for s in s_chain], args.n_words)
        _save(
            direct_out_path,
            {
                "method": f"direct{reasoning_tag}",
                **common_meta,
                "samples": samples,
                "llm_calls": args.n_samples,
                "duration_seconds": time.time() - t_start,
            },
        )

    # 2. Gibbs sampling (direct init, then single-word conditional resampling)
    gibbs_out_path = out_dir / (
        f"gibbs{reasoning_tag}_k{args.n_words}_b{args.gibbs_block_size}"
        f"_nc{args.n_chains}_seed{args.seed}.json"
    )
    if "gibbs" not in args.methods:
        pass
    elif gibbs_out_path.exists():
        print(f"Results already exist at {gibbs_out_path}, skipping...")
    else:
        print("\n--- Running Gibbs Sampling ---")
        llm = OpenAICompatLLM(
            **llm_common_kwargs,
            temperature=args.temperature,
            max_tokens=args.n_words * 24 + reasoning_extra_tokens,
        )
        template = create_template(args)
        llm_prior = LLMPrior(llm=llm, template=template, manual_reasoning=args.manual_reasoning)
        llm_prior.reasoning_prompt = llm_prior.reasoning_prompt.replace("step-by-step", "brief")
        gibbs_prior = RecordedGibbsLLMPrior(
            llm_prior=llm_prior,
            burn_in=args.burn_in,
            thinning=args.thinning,
            block_size=args.gibbs_block_size,
            sweep=args.sweep,
        )
        t_start = time.time()
        chain_results = gibbs_prior.sample_parallel(
            n_per_chain,
            [deepcopy(schema) for _ in range(args.n_chains)],
            verbose=args.verbose,
            pbar=True,
        )
        samples = _to_word_lists([s for s_chain in chain_results for s in s_chain], args.n_words)
        chain_length = args.burn_in + n_per_chain * args.thinning
        _save(
            gibbs_out_path,
            {
                "method": f"gibbs{reasoning_tag}",
                **common_meta,
                "burn_in": args.burn_in,
                "thinning": args.thinning,
                "block_size": args.gibbs_block_size,
                "sweep": args.sweep,
                "samples": samples,
                "chains": [
                    _to_word_lists(gibbs_prior.chains[i], args.n_words)
                    for i in range(args.n_chains)
                ],
                "resampled_keys": [gibbs_prior.resampled_keys[i] for i in range(args.n_chains)],
                "llm_calls": args.n_chains * (1 + chain_length),
                "duration_seconds": time.time() - t_start,
            },
        )

    # 3. Direct continuation (field-by-field, ancestral order word_1..word_N)
    direct_conti_out_path = (
        out_dir / f"direct_continuation_k{args.n_words}_nc{args.n_chains}_seed{args.seed}.json"
    )
    if "direct_continuation" not in args.methods:
        pass
    elif direct_conti_out_path.exists():
        print(f"Results already exist at {direct_conti_out_path}, skipping...")
    else:
        print("\n--- Running Direct Continuation Sampling ---")
        llm = ContinuationWordLLM(
            **llm_common_kwargs,
            temperature=args.temperature,
            max_tokens=32,
        )
        template = create_continuation_template(args)
        conti_prior = ContinuationLLMPrior(llm=llm, template=template, shuffle_variables=False)
        t_start = time.time()
        chain_results = conti_prior.sample_parallel(
            n_per_chain,
            [deepcopy(schema) for _ in range(args.n_chains)],
            verbose=args.verbose,
            pbar=True,
        )
        samples = _to_word_lists([s for s_chain in chain_results for s in s_chain], args.n_words)
        _save(
            direct_conti_out_path,
            {
                "method": "direct_continuation",
                **common_meta,
                "samples": samples,
                "llm_calls": args.n_samples * args.n_words,
                "duration_seconds": time.time() - t_start,
            },
        )

    # 4. Gibbs continuation (field-by-field conditionals inside the same scan)
    gibbs_conti_out_path = out_dir / (
        f"gibbs_continuation_k{args.n_words}_b{args.gibbs_block_size}"
        f"_nc{args.n_chains}_seed{args.seed}.json"
    )
    if "gibbs_continuation" not in args.methods:
        pass
    elif gibbs_conti_out_path.exists():
        print(f"Results already exist at {gibbs_conti_out_path}, skipping...")
    else:
        print("\n--- Running Gibbs Continuation Sampling ---")
        llm = ContinuationWordLLM(
            **llm_common_kwargs,
            temperature=args.temperature,
            max_tokens=32,
        )
        template = create_continuation_template(args)
        continuation_prior = ContinuationLLMPrior(llm=llm, template=template)
        gibbs_prior = RecordedGibbsLLMPrior(
            llm_prior=continuation_prior,
            burn_in=args.burn_in,
            thinning=args.thinning,
            block_size=args.gibbs_block_size,
            sweep=args.sweep,
        )
        t_start = time.time()
        chain_results = gibbs_prior.sample_parallel(
            n_per_chain,
            [deepcopy(schema) for _ in range(args.n_chains)],
            verbose=args.verbose,
            pbar=True,
        )
        samples = _to_word_lists([s for s_chain in chain_results for s in s_chain], args.n_words)
        chain_length = args.burn_in + n_per_chain * args.thinning
        _save(
            gibbs_conti_out_path,
            {
                "method": "gibbs_continuation",
                **common_meta,
                "burn_in": args.burn_in,
                "thinning": args.thinning,
                "block_size": args.gibbs_block_size,
                "sweep": args.sweep,
                "samples": samples,
                "chains": [
                    _to_word_lists(gibbs_prior.chains[i], args.n_words)
                    for i in range(args.n_chains)
                ],
                "resampled_keys": [gibbs_prior.resampled_keys[i] for i in range(args.n_chains)],
                "llm_calls": args.n_chains * (args.n_words + chain_length * args.gibbs_block_size),
                "duration_seconds": time.time() - t_start,
            },
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate Divergent Association Task answers with LLMs."
    )
    parser.add_argument("--model_name", type=str, default="meta-llama/Llama-3.1-8B-Instruct")
    parser.add_argument(
        "--base_url", type=str, default=None, help="Base URL for OpenAI compatible API."
    )
    parser.add_argument("--port", type=int, default=None)
    parser.add_argument("--api_key", type=str, default="NOT_A_KEY")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--n_samples", type=int, default=100, help="Number of 10-word answers per method."
    )
    parser.add_argument(
        "--n_words", type=int, default=10, help="Words per answer (Olson et al. ask for 10)."
    )

    # LLM parameters
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--n_chains", type=int, default=4)
    parser.add_argument("--gibbs_block_size", type=int, default=1)
    parser.add_argument("--burn_in", type=int, default=None)
    parser.add_argument("--thinning", type=int, default=None)
    parser.add_argument("--no_sweep", dest="sweep", action="store_false")
    parser.add_argument(
        "--manual_reasoning",
        action="store_true",
        help="Optionally add a free-text reasoning field to the JSON schema for "
        "direct/gibbs (any instruct model; continuation methods are unaffected).",
    )

    parser.add_argument(
        "--methods",
        nargs="+",
        choices=["direct", "gibbs", "direct_continuation", "gibbs_continuation"],
        default=["direct", "gibbs", "direct_continuation", "gibbs_continuation"],
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    if args.base_url is None:
        if args.port is None:
            raise ValueError("Either base_url or port must be provided.")
        args.base_url = f"http://localhost:{args.port}/v1"

    os.environ["OPENAI_API_KEY"] = args.api_key

    if not 1 <= args.gibbs_block_size <= args.n_words:
        parser.error(
            f"--gibbs_block_size ({args.gibbs_block_size}) must be between 1 "
            f"and --n_words ({args.n_words})."
        )
    if args.sweep and args.n_words % args.gibbs_block_size != 0:
        parser.error(
            f"--gibbs_block_size ({args.gibbs_block_size}) must divide --n_words "
            f"({args.n_words}) when sweep is enabled (the sweep pool refill would "
            "otherwise resample the same word twice in one block)."
        )

    if args.thinning is None:
        args.thinning = (args.n_words // args.gibbs_block_size) * 2
    if args.burn_in is None:
        args.burn_in = min(100, (args.n_samples // args.n_chains) * args.thinning // 10)
    if any("gibbs" in method for method in args.methods) and args.thinning <= 0:
        parser.error(f"--thinning must be positive, got {args.thinning}.")

    if args.model_name not in MODEL_NAME_TO_TYPE:
        parser.error(
            f"Unknown model {args.model_name!r}; add it to MODEL_NAME_TO_TYPE in "
            "divergent_association_task/utils.py."
        )
    args.model_type = MODEL_NAME_TO_TYPE[args.model_name]

    if args.manual_reasoning and args.model_type != "instruct":
        parser.error(
            f"--manual_reasoning is only supported for instruct models; got "
            f"{args.model_type} model {args.model_name!r}."
        )

    random.seed(args.seed)
    np.random.seed(args.seed)

    if args.n_samples % args.n_chains != 0:
        raise ValueError(
            f"n_samples ({args.n_samples}) must be divisible by n_chains ({args.n_chains})."
        )

    main(args)
